// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBToyX-Dr9NaW1tlDa8VLxaM3iaTZMGlrU',
    appId: '1:1091927884473:web:195a8ef114fd869e701168',
    messagingSenderId: '1091927884473',
    projectId: 'senior-project-2022-16cdc',
    authDomain: 'senior-project-2022-16cdc.firebaseapp.com',
    storageBucket: 'senior-project-2022-16cdc.appspot.com',
    measurementId: 'G-6KFC2EFKFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_PqnxD0BZRSdKviCslNYBtb5JSMHpQkk',
    appId: '1:1091927884473:android:dbc5bfe1337b4f47701168',
    messagingSenderId: '1091927884473',
    projectId: 'senior-project-2022-16cdc',
    storageBucket: 'senior-project-2022-16cdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKP50lI6GKeikGh7MgwHq0IHKmos2qjKQ',
    appId: '1:1091927884473:ios:a098e951890e73e8701168',
    messagingSenderId: '1091927884473',
    projectId: 'senior-project-2022-16cdc',
    storageBucket: 'senior-project-2022-16cdc.appspot.com',
    iosClientId: '1091927884473-em3fvaolhpjb7hpbuksgogkg74412sb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberCopy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKP50lI6GKeikGh7MgwHq0IHKmos2qjKQ',
    appId: '1:1091927884473:ios:a098e951890e73e8701168',
    messagingSenderId: '1091927884473',
    projectId: 'senior-project-2022-16cdc',
    storageBucket: 'senior-project-2022-16cdc.appspot.com',
    iosClientId: '1091927884473-em3fvaolhpjb7hpbuksgogkg74412sb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberCopy',
  );
}
